version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
s3_bucket = "marga-deploy-bucket-staging"
s3_prefix = "todo-list-aws"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
